# Repository defaults for Kruin dialog
structure.type=1
defaults.profile=kruin
projections.show=true
projections.left.enabled=true
projections.right.enabled=false
projections.top.enabled=true
projections.bottom.enabled=false
structure.offset.left=2
structure.offset.right=2
structure.offset.top=2
structure.offset.bottom=2
projection.left.position=2
projection.right.position=30
projection.top.position=0
projection.bottom.position=30
grid.column.width=20
grid.row.height=20
